# Generated by Django 4.1.7 on 2023-03-09 08:19

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('image', pyuploadcare.dj.models.ImageField()),
            ],
        ),
    ]
